social-media si addres nu functioneaza
DragosU25/team-project pull request #15
Opened 2024-02-08 16:18 UTC by SuciuOana97

2024-02-08 17:10 UTC, DragosU25 requested changes

2024-02-08 17:10 UTC, DragosU25 commented on src/partials/footer.html
> +      </div>
aici tebuie sa fie un singur link.
Asta e structura:
<a href=">
<div>
<svg>
<use></use>
</svg>
<p>FRESH HARVEST BOX</p>
</div>
</a>

2024-02-08 17:10 UTC, DragosU25 commented on src/partials/footer.html
> +      <nav class="navigation-footer list">
este un singur nav pe pagina. aici poti lasa doar ul

2024-02-08 17:10 UTC, DragosU25 commented on src/partials/footer.html
> +      <li>
elementele li fara un ul sau ol sunt inutile, te rog sa introduci toate elementele li intr un ul cu clasa list

2024-02-08 17:10 UTC, DragosU25 commented on src/partials/footer.html
> +        </ul>
poti scrie direct 2 link uri fara sa le adaugi intr o lista
nu cred ca este necesar

2024-02-08 17:26 UTC, DragosU25 requested changes

2024-02-08 17:26 UTC, DragosU25 commented on src/partials/footer.html
>            <li class="footer-socials-item">
asta este structura:
<ul class="list social-media-list">
            <li>
              <a href="" class="link">
                <div class="social-media-container">
                  <svg width="28" height="28" class="social-mdia-icon">
                    <use href="./images/icons.svg#icon-facebok"></use>
                  </svg>
                </div>
              </a>
            </li>

pentru ca ulterior o sa trebuiasca sa stilizezi containerul cu acel border, padding etc

2024-02-08 17:26 UTC, DragosU25 commented on src/partials/footer.html
> +        </address>
aici e ok, mai adauga clasa list pe ul

2024-02-08 21:31 UTC, DragosU25 requested changes

2024-02-08 21:31 UTC, DragosU25 commented on src/partials/footer.html
> +      </a>
aici ar fi mai bine ca a sa cuprinda un div.logo-container. pentru ca o sa trebuiasca sa ai un gap intre icon si span si ar fi mult mai usor daca ai face asa. Deci link ul sa cuprinda divul.logo-container si in interiorul lui sa fie svg ul si span ul

2024-02-08 21:48 UTC, DragosU25 requested changes

2024-02-08 21:48 UTC, DragosU25 commented on src/partials/footer.html
> +        </a>
acum am vazut ca ai si body, sterge -l pentru ca nu ti trebuie. apoi aici cel mai bine ar fi sa fie asa:
<a href="./index.html" class="link">
<div class="logo-container">
 <svg width="16" height="16" class="footer-logo-img">
            <use href="../images/icons.svg#logo-icon"></use>
          </svg>
          <span class="footer-logo-text">FRESH HARVEST BOX</span>
</div>
</a>

Sorry, dar o sa ti fie mult mai usor la css

2024-02-09 16:44 UTC, SuciuOana97 commented
fara body nu imi apar elementele de social media .... fb, insta si youtube

2024-02-09 19:46 UTC, closed without merging